// <auto-generated />
namespace ViajesTransparentes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class altadeetiquetasdevalidacionenmodelopersona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altadeetiquetasdevalidacionenmodelopersona));
        
        string IMigrationMetadata.Id
        {
            get { return "201409162125165_alta de etiquetas de validacion en modelo persona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
