// <auto-generated />
namespace ViajesTransparentes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class altademodeloServidorPublicoIFAI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altademodeloServidorPublicoIFAI));
        
        string IMigrationMetadata.Id
        {
            get { return "201409150045570_alta de modelo Servidor Publico IFAI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
